### ISSUE TITLE
Error when plotting community with only one node

### ISSUE THREAD

**Issue by plutonium-94** [paulbrodersen/netgraph#33]
Code example:
```
import networkx as nx
import netgraph as ng
import matplotlib.pyplot as plt

graph = nx.Graph([(0, 1)])
ng.Graph(graph, node_layout='community', node_layout_kwargs={'node_to_community': {0: 0, 1: 1}})
plt.show()
```

Error trace:
```
Traceback (most recent call last):
  File "D:\Projects\PycharmProjects\CommunityDetection\netgraph_bug.py", line 7, in <module>
    ng.Graph(graph, node_layout='community', node_layout_kwargs={'node_to_community': {0: 0, 1: 1}})
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_main.py", line 1306, in __init__
    super().__init__(edges, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_main.py", line 286, in __init__
    self.node_positions = self._initialize_node_layout(
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_main.py", line 426, in _initialize_node_layout
    return self._get_node_positions(node_layout, node_layout_kwargs, origin, scale)
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_main.py", line 441, in _get_node_positions
    node_positions = get_community_layout(
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_node_layout.py", line 62, in wrapped_layout_function
    return layout_function(edges, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_node_layout.py", line 870, in get_community_layout
    relative_node_positions = _get_node_positions(edges, node_to_community)
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_node_layout.py", line 931, in _get_node_positions
    subgraph_node_positions = get_fruchterman_reingold_layout(
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_node_layout.py", line 62, in wrapped_layout_function
    return layout_function(edges, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_node_layout.py", line 257, in get_fruchterman_reingold_layout
    assert len(edges) > 0, "The list of edges has to be non-empty."
AssertionError: The list of edges has to be non-empty.
```

Package versions:
```
networkx=2.6.3
netgraph=4.6.1
```

**Comment by paulbrodersen** [comment]
Thanks for the bug report and great MWE. The issue should (hopefully) be fixed in the latest release. I am swamped with work today so I can't test the changes extensively and would hence appreciate feedback if the layout now works as expected.

**Comment by plutonium-94** [comment]
I have already updated to the latest version of netgraph, and it works as expected now. Thanks a lot! But there is another problem I just found:

Code example:
```
import networkx as nx
import netgraph as ng
import matplotlib.pyplot as plt

graph = nx.empty_graph(1)
ng.Graph(graph)
plt.show()
```

Error trace:
```
Traceback (most recent call last):
  File "D:\Projects\PycharmProjects\CommunityDetection\netgraph_bug.py", line 7, in <module>
    ng.Graph(graph)
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_main.py", line 1307, in __init__
    super().__init__(edges, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_main.py", line 286, in __init__
    self.node_positions = self._initialize_node_layout(
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_main.py", line 426, in _initialize_node_layout
    return self._get_node_positions(node_layout, node_layout_kwargs, origin, scale)
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_main.py", line 435, in _get_node_positions
    node_positions = get_fruchterman_reingold_layout(
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_node_layout.py", line 62, in wrapped_layout_function
    return layout_function(edges, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_node_layout.py", line 258, in get_fruchterman_reingold_layout
    assert len(edges) > 0, "The list of edges has to be non-empty."
AssertionError: The list of edges has to be non-empty.
```

**Comment by paulbrodersen** [comment]
For obvious reasons, most node layout and edge routing algorithms are undefined for empty graphs. Throwing an exception is the right course of action, in my opinion. Why do you want to plot empty graphs?

**Comment by plutonium-94** [comment]
Plotting a completely empty graph with no nodes and edges may be meaningless, but `nx.empty_graph(1)` creates a graph with only one node and no edge, which is visually representable.

**Comment by plutonium-94** [comment]
In fact I was plotting communities in network, and the algorithm classified each isolated node as one community. The situation is similar to:

```
import networkx as nx
import netgraph as ng
import matplotlib.pyplot as plt

graph = nx.empty_graph(2)
ng.Graph(graph, node_layout='community', node_layout_kwargs={'node_to_community': {0: 0, 1: 1}})
plt.show()
```

And it caused the error below:

```
C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_node_layout.py:863: UserWarning: Graph contains a single community. Unable to compute a community layout. Computing spring layout instead.
  warnings.warn("Graph contains a single community. Unable to compute a community layout. Computing spring layout instead.")
Traceback (most recent call last):
  File "D:\Projects\PycharmProjects\CommunityDetection\netgraph_bug.py", line 7, in <module>
    ng.Graph(graph, node_layout='community', node_layout_kwargs={'node_to_community': {0: 0, 1: 1}})
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_main.py", line 1307, in __init__
    super().__init__(edges, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_main.py", line 286, in __init__
    self.node_positions = self._initialize_node_layout(
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_main.py", line 426, in _initialize_node_layout
    return self._get_node_positions(node_layout, node_layout_kwargs, origin, scale)
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_main.py", line 441, in _get_node_positions
    node_positions = get_community_layout(
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_node_layout.py", line 62, in wrapped_layout_function
    return layout_function(edges, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_node_layout.py", line 864, in get_community_layout
    return get_fruchterman_reingold_layout(edges, origin=origin, scale=scale)
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_node_layout.py", line 62, in wrapped_layout_function
    return layout_function(edges, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\CommunityDetection\lib\site-packages\netgraph\_node_layout.py", line 258, in get_fruchterman_reingold_layout
    assert len(edges) > 0, "The list of edges has to be non-empty."
AssertionError: The list of edges has to be non-empty.
```

**Comment by paulbrodersen** [comment]
Plotting graphs with just a single node is now supported in the latest version on github.

**Comment by Alexander-Wilms** [comment]
I still encounter this error when plotting a network with a single node with version 4.11.7:

```python
import networkx as nx
import netgraph as ng
import matplotlib.pyplot as plt

G = nx.Graph()
G.add_node('A')
#nx.draw(G)
ng.Graph(G)
plt.show()
```

`AssertionError: The list of edges has to be non-empty.`

**Comment by paulbrodersen** [comment]
@Alexander-Wilms Thanks, I incorporated your suggestion with minor modifications. You are listed as a co-author in the commit but I had to use your no-reply github email address as yours wasn't on your profile.
