### ISSUE TITLE
Opacity behavior when removing vertex 

### ISSUE THREAD

**Issue by fsoupimenta** [paulbrodersen/netgraph#66]
Hello,
I'm working on a [project](https://github.com/GraphFilter/GraphFilter) that uses Netgraph, and when i remove a vertex that has one of its adjacent ones with opacity 1, the opacity of the other vertices bugs and they behave strangely.

 - It's hard to explain, so I made a gif to demonstrate the situation:

![Graph-Filter-test-2023-03-29-11-59-00](https://user-images.githubusercontent.com/108306295/234742258-b39897fe-7d17-4a16-9523-bf6f4306ddfd.gif)

 - In my console, i got the following traceback:
```
Traceback (most recent call last):
  File "C:\Users\Fernando Pimenta\Documents\Github\GraphFilter\venv\lib\site-packages\matplotlib\cbook\__init__.py", line 307, in process
    func(*args, **kwargs)
  File "C:\Users\Fernando Pimenta\Documents\Github\GraphFilter\venv\lib\site-packages\netgraph\_interactive_variants.py", line 203, in _on_motion
    super()._on_motion(event)
  File "C:\Users\Fernando Pimenta\Documents\Github\GraphFilter\venv\lib\site-packages\netgraph\_main.py", line 2621, in _on_motion
    EmphasizeOnHoverGraph._on_motion(self, event)
  File "C:\Users\Fernando Pimenta\Documents\Github\GraphFilter\venv\lib\site-packages\netgraph\_main.py", line 2071, in _on_motion
    artist.set_alpha(self._base_alpha[artist])
KeyError: <netgraph._artists.EdgeArtist object at 0x000001670E5BC700>
```

**Comment by paulbrodersen** [comment]
Sorry, I had not considered this edge case. Steps to reproduce: 

1) Select a node.
2) Hover over an incident edge.
3) Delete node while hovering over the edge. 

Removing the node also removes the edge, but the edge is still in the list of highlighted artists. The attempt to reverse the opacity results in the error.

**Comment by paulbrodersen** [comment]
The latest commit mitigates the issue such that it should no longer result in an error, and the appearance of all artist should be restored to normal on the first movement.

Note to future self: for some reason, the artists for the de-emphasized edges aren't removed from `self.deemphasized_artists` when deleting the edge, although we explicitly do so in `_interactive_variants.MutableGraph._delete_edge`.
